version: "3.4"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Milosqui11
      DOCKER_HOST: "127.0.0.1"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro